<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DailyCases extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'set_date',
        'type',
        'total_active',
        'total_active_unvaccinated',
        'total_active_halfvax',
        'total_active_fullvax',
        'total_active_booster',
        'total_recoveries',
        'total_recoveries_unvaccinated',
        'total_recoveries_halfvax',
        'total_recoveries_fullvax',
        'total_recoveries_booster',
        'total_deaths',
        'total_deaths_unvaccinated',
        'total_deaths_halfvax',
        'total_deaths_fullvax',
        'total_deaths_booster',
        'new_cases',
        'new_cases_unvaccinated',
        'new_cases_halfvax',
        'new_cases_fullvax',
        'new_cases_booster',
        'late_cases',
        'late_cases_unvaccinated',
        'late_cases_halfvax',
        'late_cases_fullvax',
        'late_cases_booster',
        'new_recoveries',
        'new_recoveries_unvaccinated',
        'new_recoveries_halfvax',
        'new_recoveries_fullvax',
        'new_recoveries_booster',
        'late_recoveries',
        'late_recoveries_unvaccinated',
        'late_recoveries_halfvax',
        'late_recoveries_fullvax',
        'late_recoveries_booster',
        'new_deaths',
        'new_deaths_unvaccinated',
        'new_deaths_halfvax',
        'new_deaths_fullvax',
        'new_deaths_booster',
        'total_all_confirmed_cases',
        'total_all_suspected_probable_cases',
        'facility_one_count',
        'facility_two_count',
        'hq_count',
        'hospital_count',
        'active_asymptomatic_count',
        'active_mild_with_comorbid_count',
        'active_mild_without_comorbid_count',
        'active_moderate_count',
        'active_severe_count',
        'active_critical_count',
        'active_male_count',
        'active_female_count',
        'active_agegroup1_count',
        'active_agegroup2_count',
        'active_agegroup3_count',
        'active_agegroup4_count',
        'active_agegroup5_count',
        'active_agegroup6_count',
        'reinfection_active',
        'reinfection_recovered',
        'reinfection_deaths',
        'reinfection_total',

        'rtpcr_confirmed_count_currentyear',
        'antigen_positive_count_currentyear',
        'recoveries_currentyear',
        'deaths_currentyear',
        'currentyear_asymptomatic',
        'currentyear_mild',
        'currentyear_moderate',
        'currentyear_severe',
        'currentyear_critical',

        'barangay_list',
        'barangay_rtpcr_counts',
        'barangay_antigen_counts',
        'barangay_dailyrecovered_counts',
    ];
}
